# Generated by Django 5.2.5 on 2026-02-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline_en', models.CharField(default="Fearless and Unbiased - Gujarat's most trusted weekly newspaper.", max_length=200)),
                ('tagline_gu', models.CharField(blank=True, max_length=200)),
                ('tagline_hi', models.CharField(blank=True, max_length=200)),
                ('about_title_en', models.CharField(default='About Us', max_length=120)),
                ('about_title_gu', models.CharField(blank=True, max_length=120)),
                ('about_title_hi', models.CharField(blank=True, max_length=120)),
                ('about_description_en', models.TextField(blank=True)),
                ('about_description_gu', models.TextField(blank=True)),
                ('about_description_hi', models.TextField(blank=True)),
                ('editor_name', models.CharField(default='Japan A. Shah', max_length=120)),
                ('editor_title_en', models.CharField(default='Editor in Chief & Owner', max_length=120)),
                ('editor_title_gu', models.CharField(blank=True, max_length=120)),
                ('editor_title_hi', models.CharField(blank=True, max_length=120)),
                ('editor_bio_en', models.TextField(blank=True)),
                ('editor_bio_gu', models.TextField(blank=True)),
                ('editor_bio_hi', models.TextField(blank=True)),
                ('mission_en', models.TextField(blank=True)),
                ('mission_gu', models.TextField(blank=True)),
                ('mission_hi', models.TextField(blank=True)),
                ('publication_description_en', models.TextField(blank=True)),
                ('publication_description_gu', models.TextField(blank=True)),
                ('publication_description_hi', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, default='https://www.kanamexpress.com')),
                ('contact_phone_primary', models.CharField(blank=True, max_length=30)),
                ('contact_phone_secondary', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
