# Generated by Django 5.2.5 on 2026-02-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='value1_desc_en',
            field=models.CharField(blank=True, default='Committed to truthful reporting', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value1_desc_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value1_desc_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value1_title_en',
            field=models.CharField(blank=True, default='Truth', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value1_title_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value1_title_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_desc_en',
            field=models.CharField(blank=True, default='Serving our community', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_desc_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_desc_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_title_en',
            field=models.CharField(blank=True, default='Community', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_title_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_title_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_desc_en',
            field=models.CharField(blank=True, default='Precise and verified news', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_desc_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_desc_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_title_en',
            field=models.CharField(blank=True, default='Accuracy', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_title_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_title_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_desc_en',
            field=models.CharField(blank=True, default='Ethical journalism', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_desc_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_desc_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_title_en',
            field=models.CharField(blank=True, default='Integrity', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_title_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_title_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
