# Generated by Django 5.2.5 on 2026-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_value1_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3691.5!2d72.95!3d21.9!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sJambusar%2C%20Gujarat!5e0!3m2!1sen!2sin!4v1234567890'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_name_en',
            field=models.CharField(blank=True, default='Kanam Express - Weekly Newspaper', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_name_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization_name_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_en',
            field=models.TextField(blank=True, default='Mon - Fri: 9:00 AM - 6:00 PM\nSaturday: 10:00 AM - 4:00 PM\nSunday: Closed'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_gu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_hi',
            field=models.TextField(blank=True),
        ),
    ]
