# Generated by Django 5.2.5 on 2026-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_google_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_desc_en',
            field=models.TextField(blank=True, default='Reach millions through our daily newspaper editions across Gujarat.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_desc_gu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_desc_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_tags_en',
            field=models.CharField(blank=True, default='Full Page, Half Page, Quarter Page, Classified', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_tags_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_tags_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_title_en',
            field=models.CharField(blank=True, default='Print Advertising', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_title_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format1_title_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_desc_en',
            field=models.TextField(blank=True, default='Target your audience with precision on our website and mobile app.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_desc_gu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_desc_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_tags_en',
            field=models.CharField(blank=True, default='Banner Ads, Native Ads, Video Ads, Sponsored Content', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_tags_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_tags_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_title_en',
            field=models.CharField(blank=True, default='Digital Advertising', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_title_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format2_title_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_desc_en',
            field=models.TextField(blank=True, default='Advertise on Sandesh News channel and reach viewers across India.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_desc_gu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_desc_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_tags_en',
            field=models.CharField(blank=True, default='Spot Ads, Aston Bands, L-Bands, Sponsorships', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_tags_gu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_tags_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_title_en',
            field=models.CharField(blank=True, default='TV Advertising', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_title_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_format3_title_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat1_label_en',
            field=models.CharField(blank=True, default='Monthly Readers', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat1_label_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat1_label_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat1_value',
            field=models.CharField(blank=True, default='50M+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat2_label_en',
            field=models.CharField(blank=True, default='Page Views', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat2_label_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat2_label_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat2_value',
            field=models.CharField(blank=True, default='100M+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat3_label_en',
            field=models.CharField(blank=True, default='Print Editions', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat3_label_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat3_label_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat3_value',
            field=models.CharField(blank=True, default='15+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat4_label_en',
            field=models.CharField(blank=True, default='In Gujarat', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat4_label_gu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat4_label_hi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adv_stat4_value',
            field=models.CharField(blank=True, default='#1', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advertise_desc_en',
            field=models.TextField(blank=True, default='Reach millions of engaged readers across Gujarat through print, digital, and broadcast media.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advertise_desc_gu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advertise_desc_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advertise_title_en',
            field=models.CharField(blank=True, default='Advertise With Us', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advertise_title_gu',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advertise_title_hi',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
