# Generated by Django 5.2.5 on 2026-03-11 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='police_verification',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
