# Generated by Django 5.2.5 on 2026-07-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_notification_news_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CAREER_APPLICATION', 'Career Application'), ('CONTACT_MESSAGE', 'Contact Message'), ('NEWS_ARTICLE', 'News Article'), ('VIDEO_CONTENT', 'Video Content'), ('REEL_CONTENT', 'Reel Content'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
