# Generated by Django 5.2.5 on 2026-02-06 06:50

import advertisements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('placement', models.CharField(choices=[('TOP', 'Top'), ('SIDEBAR_LEFT', 'Sidebar Left'), ('SIDEBAR_RIGHT', 'Sidebar Right'), ('IN_ARTICLE', 'In Article'), ('FOOTER', 'Footer'), ('POPUP', 'Popup')], max_length=20)),
                ('ad_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('HTML', 'HTML Snippet')], default='IMAGE', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], default='DRAFT', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=advertisements.models.ad_asset_upload_to)),
                ('video', models.FileField(blank=True, null=True, upload_to=advertisements.models.ad_asset_upload_to)),
                ('html_snippet', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('advertiser_name', models.CharField(blank=True, max_length=200)),
                ('advertiser_email', models.EmailField(blank=True, max_length=254)),
                ('advertiser_phone', models.CharField(blank=True, max_length=30)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active', 'status'], name='advertiseme_placeme_90856f_idx'), models.Index(fields=['start_at', 'end_at'], name='advertiseme_start_a_e251f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=200)),
                ('advertiser_email', models.EmailField(max_length=254)),
                ('advertiser_phone', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('placement', models.CharField(choices=[('TOP', 'Top'), ('SIDEBAR_LEFT', 'Sidebar Left'), ('SIDEBAR_RIGHT', 'Sidebar Right'), ('IN_ARTICLE', 'In Article'), ('FOOTER', 'Footer'), ('POPUP', 'Popup')], max_length=20)),
                ('ad_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('HTML', 'HTML Snippet')], default='IMAGE', max_length=10)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='advertiseme_status_164eb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoogleAdSenseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('placement', models.CharField(choices=[('TOP', 'Top'), ('SIDEBAR_LEFT', 'Sidebar Left'), ('SIDEBAR_RIGHT', 'Sidebar Right'), ('IN_ARTICLE', 'In Article'), ('FOOTER', 'Footer'), ('POPUP', 'Popup')], max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('slot_id', models.CharField(blank=True, max_length=64)),
                ('format', models.CharField(blank=True, max_length=64)),
                ('responsive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['placement', 'order', 'name'],
                'indexes': [models.Index(fields=['placement', 'is_active', 'order'], name='advertiseme_placeme_11d95e_idx')],
            },
        ),
    ]
