# Generated by Django 5.2.5 on 2026-02-13 05:41

import advertisements.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=advertisements.models.ad_asset_upload_to, validators=[utils.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=advertisements.models.ad_asset_upload_to, validators=[utils.validators.validate_file_size]),
        ),
    ]
