"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# In production, set DEBUG=False via environment variable.
DEBUG = config("DEBUG", default=True, cast=bool)

_allowed_hosts = config("ALLOWED_HOSTS", default="")
# ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

ALLOWED_HOSTS = ["newsportal.com", "www.newsportal.com", "194.164.151.91"]

# Application definition
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'users',
    'news',
    'advertisements',
    'contact',
    'analytics',
    'site_settings',
    'careers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='news_portal_db'),
        'USER': config('DB_USER', default='news_user'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Use a lightweight in-memory DB when running automated tests.
if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

_cors_allowed_origins = config("CORS_ALLOWED_ORIGINS", default="")
if _cors_allowed_origins:
    # Example (env): CORS_ALLOWED_ORIGINS=https://kanamexpress.com,https://admin.kanamexpress.com
    CORS_ALLOWED_ORIGINS = [
        o.strip() for o in _cors_allowed_origins.split(",") if o.strip()
    ]
else:
    # Local development defaults
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",  # React default port
        "http://127.0.0.1:3000",
        "http://localhost:8080",  # Vite frontend (kanam_express)
        "http://127.0.0.1:8080",
    ]

CORS_ALLOW_CREDENTIALS = True

_csrf_trusted = config("CSRF_TRUSTED_ORIGINS", default="")
if _csrf_trusted:
    # Example (env): CSRF_TRUSTED_ORIGINS=https://kanamexpress.com,https://admin.kanamexpress.com
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in _csrf_trusted.split(",") if o.strip()
    ]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# File upload settings - allow large video files
# Files larger than this will be streamed to disk instead of kept in memory
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB - files larger than this go to disk
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
# No limit on actual file size - removed validators from models

# Custom user model
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    # Throttling: disabled when DEBUG (development); enabled when DEBUG=False (deploy).
    'DEFAULT_THROTTLE_CLASSES': () if DEBUG else (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100000/hour' if DEBUG else '100/hour',
        'user': '100000/hour' if DEBUG else '1000/hour',
        'auth': '100000/hour' if DEBUG else '10/hour',
        'contact': '100000/minute' if DEBUG else '5/minute',
        'ads_requests': '100000/hour' if DEBUG else '10/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Email (contact form + password reset)
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@newsportal.local")
CONTACT_ADMIN_EMAIL = config("CONTACT_ADMIN_EMAIL", default="admin@newsportal.local")
# Frontend URL for password reset link (user lands here with token in query)
FRONTEND_RESET_PASSWORD_URL = config(
    "FRONTEND_RESET_PASSWORD_URL",
    # Default to Vite dev server; override in production via env
    default="http://localhost:8080/reset-password",
)

# API documentation (drf-spectacular)
SPECTACULAR_SETTINGS = {
    "TITLE": "News Portal API",
    "DESCRIPTION": "Backend API for the News Portal application.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Logging
_log_dir = os.path.join(BASE_DIR, "logs")
if not DEBUG:
    try:
        os.makedirs(_log_dir, exist_ok=True)
    except OSError:
        pass
_use_file_logging = not DEBUG and os.path.isdir(_log_dir)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": config("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
if _use_file_logging:
    LOGGING["handlers"]["file"] = {
        "class": "logging.FileHandler",
        "filename": os.path.join(_log_dir, "django.log"),
        "formatter": "verbose",
    }
    LOGGING["root"]["handlers"].append("file")


# Security hardening for production (HTTPS, secure cookies, HSTS).
if not DEBUG:
    # Cookies should only be sent over HTTPS in production
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Prevent client-side JS from accessing session/CSRF cookies
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

    # Redirect all HTTP to HTTPS (can be disabled via env if needed behind a proxy)
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)

    # HSTS – tell browsers to always use HTTPS for this domain
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Additional browser security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
else:
    # In local dev, avoid forced HTTPS redirect
    SECURE_SSL_REDIRECT = False

# External Cricket API (RapidAPI or similar)
# These settings allow the backend to proxy live cricket news/scores
CRICKET_API_ENABLED = config("CRICKET_API_ENABLED", default=False, cast=bool)
CRICKET_API_BASE_URL = config("CRICKET_API_BASE_URL", default="")
CRICKET_API_HOST = config("CRICKET_API_HOST", default="")
CRICKET_API_KEY = config("CRICKET_API_KEY", default="")
CRICKET_MATCHES_API_URL = config("CRICKET_MATCHES_API_URL", default="")