# Generated by Django 5.2.5 on 2026-02-06 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='newsview',
            index=models.Index(fields=['article', 'viewed_at'], name='analytics_n_article_9f81cf_idx'),
        ),
        migrations.AddIndex(
            model_name='newsview',
            index=models.Index(fields=['user', 'viewed_at'], name='analytics_n_user_id_595356_idx'),
        ),
    ]
