# Generated by Django 5.2.5 on 2026-03-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reel',
            new_name='reels_reel_status_828f08_idx',
            old_name='reels_reel_status_published_idx',
        ),
        migrations.RenameIndex(
            model_name='reel',
            new_name='reels_reel_is_appr_586be6_idx',
            old_name='reels_reel_approved_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reel',
            new_name='reels_reel_is_feat_e1af74_idx',
            old_name='reels_reel_featured_trending_idx',
        ),
        migrations.RenameIndex(
            model_name='reel',
            new_name='reels_reel_created_71ec95_idx',
            old_name='reels_reel_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='reel',
            new_name='reels_reel_author__7eeee6_idx',
            old_name='reels_reel_author_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reelcategory',
            new_name='reels_reelc_is_acti_67defc_idx',
            old_name='reels_reelca_is_acti_idx',
        ),
    ]
