# Generated by Django 5.2.5 on 2026-02-06 06:50

import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('REEL', 'Reel'), ('YOUTUBE', 'YouTube')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=news.models.media_upload_to)),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.media_upload_to)),
                ('youtube_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=news.models.media_upload_to)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_hi', models.CharField(blank=True, max_length=300)),
                ('title_gu', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_hi', models.TextField(blank=True)),
                ('summary_gu', models.TextField(blank=True)),
                ('content_en', models.TextField()),
                ('content_hi', models.TextField(blank=True)),
                ('content_gu', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=news.models.featured_image_upload_to)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Article'), ('REEL', 'Reel'), ('YOUTUBE', 'YouTube'), ('VIDEO', 'Video')], default='ARTICLE', max_length=12)),
                ('primary_language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('GU', 'Gujarati')], default='GU', max_length=2)),
                ('is_breaking', models.BooleanField(default=False)),
                ('is_top', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_hi', models.CharField(blank=True, max_length=120)),
                ('name_gu', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_hi', models.CharField(blank=True, max_length=120)),
                ('name_gu', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_en'],
                'indexes': [models.Index(fields=['is_active', 'name_en'], name='news_catego_is_acti_3f4449_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
