# Generated by Django 5.2.5 on 2026-02-06 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category'),
        ),
        migrations.AddField(
            model_name='media',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='news.section'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news.section'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.tag'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['article', 'media_type', 'order'], name='news_media_article_c526d6_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['article', 'created_at'], name='news_like_article_1b9c16_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_like_per_user_article'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'created_at'], name='news_commen_article_133009_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='news_commen_parent__f18116_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_approved'], name='news_commen_is_appr_67abdb_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['parent'], name='news_sectio_parent__a176b6_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active', 'order'], name='news_sectio_is_acti_f5e334_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['status', 'published_at'], name='news_newsar_status_e12c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_breaking', 'status', 'published_at'], name='news_newsar_is_brea_43cb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_top', 'status', 'published_at'], name='news_newsar_is_top_f4c31b_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['section', 'status', 'published_at'], name='news_newsar_section_65f1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category', 'status', 'published_at'], name='news_newsar_categor_b34c5a_idx'),
        ),
    ]
