# Generated by Django 5.2.5 on 2026-02-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
