# Generated by Django 5.2.5 on 2026-02-09 05:11

from django.db import migrations


def backfill_likes_count(apps, schema_editor):
    NewsArticle = apps.get_model("news", "NewsArticle")
    Like = apps.get_model("news", "Like")
    for article in NewsArticle.objects.all():
        count = Like.objects.filter(article=article).count()
        if count:
            NewsArticle.objects.filter(pk=article.pk).update(likes_count=count)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_add_likes_count"),
    ]

    operations = [
        migrations.RunPython(backfill_likes_count, noop),
    ]
