# Generated by Django 5.2.5 on 2026-02-11 09:57

import django.db.models.deletion
import news.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_approve_existing_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_hi', models.CharField(blank=True, max_length=300)),
                ('title_gu', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_hi', models.TextField(blank=True)),
                ('description_gu', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=news.models.media_upload_to, validators=[utils.validators.validate_image_size])),
                ('file', models.FileField(blank=True, null=True, upload_to=news.models.media_upload_to, validators=[utils.validators.validate_file_size])),
                ('youtube_url', models.URLField(blank=True)),
                ('primary_language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('GU', 'Gujarati')], default='GU', max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_hi', models.CharField(blank=True, max_length=300)),
                ('title_gu', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_hi', models.TextField(blank=True)),
                ('description_gu', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=news.models.media_upload_to, validators=[utils.validators.validate_image_size])),
                ('file', models.FileField(blank=True, null=True, upload_to=news.models.media_upload_to, validators=[utils.validators.validate_file_size])),
                ('youtube_url', models.URLField(blank=True)),
                ('primary_language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('GU', 'Gujarati')], default='GU', max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='news_catego_is_appr_8ce2e1_idx',
            old_name='news_catego_is_appr_idx',
        ),
        migrations.RenameIndex(
            model_name='section',
            new_name='news_sectio_is_appr_883be8_idx',
            old_name='news_sectio_is_appr_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='news_tag_is_appr_a472e7_idx',
            old_name='news_tag_is_appr_idx',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=news.models.media_upload_to, validators=[utils.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.media_upload_to, validators=[utils.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.media_upload_to, validators=[utils.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.featured_image_upload_to, validators=[utils.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='reelcontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='news.category'),
        ),
        migrations.AddField(
            model_name='reelcontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='news.section'),
        ),
        migrations.AddField(
            model_name='reelcontent',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_items', to='news.tag'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='news.category'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='news.section'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_items', to='news.tag'),
        ),
        migrations.AddIndex(
            model_name='reelcontent',
            index=models.Index(fields=['status', 'published_at'], name='news_reelco_status_3c7144_idx'),
        ),
        migrations.AddIndex(
            model_name='reelcontent',
            index=models.Index(fields=['section', 'status', 'published_at'], name='news_reelco_section_395eef_idx'),
        ),
        migrations.AddIndex(
            model_name='reelcontent',
            index=models.Index(fields=['category', 'status', 'published_at'], name='news_reelco_categor_1d39a5_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['status', 'published_at'], name='news_videoc_status_125f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['section', 'status', 'published_at'], name='news_videoc_section_fafe73_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['category', 'status', 'published_at'], name='news_videoc_categor_0a5157_idx'),
        ),
    ]
