# Generated by Django 5.2.5 on 2026-02-12 06:34

import news.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_reelcontent_videocontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=news.models.media_upload_to),
        ),
        migrations.AlterField(
            model_name='reelcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=news.models.media_upload_to),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=news.models.media_upload_to),
        ),
    ]
