# Generated by Django 5.2.5 on 2026-02-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_districts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='district',
            new_name='news_distri_section_424abd_idx',
            old_name='news_distri_section_iaor_idx',
        ),
    ]
