# Generated by Django 5.2.5 on 2026-02-13 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_news_distri_section_iaor_idx_news_distri_section_424abd_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.district'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['district', 'status', 'published_at'], name='news_newsar_distric_3c08c3_idx'),
        ),
    ]
