# Generated by Django 5.2.5 on 2026-03-07 06:07

from django.db import migrations, connection


def check_and_rename_if_needed(apps, schema_editor):
    """
    This migration is a duplicate of 0012. Since 0012 already handled the rename,
    this migration should only run if is_featured still exists (which shouldn't happen).
    If is_trending already exists, do nothing.
    """
    with connection.cursor() as cursor:
        # Check if is_featured column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='news_newsarticle' AND column_name='is_featured'
        """)
        has_is_featured = cursor.fetchone() is not None
        
        # Check if is_trending column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='news_newsarticle' AND column_name='is_trending'
        """)
        has_is_trending = cursor.fetchone() is not None
        
        # Only rename if is_featured exists and is_trending doesn't
        # (This shouldn't happen since 0012 already handled it, but just in case)
        if has_is_featured and not has_is_trending:
            cursor.execute("""
                ALTER TABLE news_newsarticle 
                RENAME COLUMN is_featured TO is_trending
            """)
        # If is_trending already exists (normal case after 0012), do nothing


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: rename is_trending back to is_featured if it exists
    """
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='news_newsarticle' AND column_name='is_trending'
        """)
        has_is_trending = cursor.fetchone() is not None
        
        if has_is_trending:
            cursor.execute("""
                ALTER TABLE news_newsarticle 
                RENAME COLUMN is_trending TO is_featured
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_is_featured_is_trending'),
    ]

    operations = [
        migrations.RunPython(check_and_rename_if_needed, reverse_migration),
    ]
