# Generated by Django 5.2.5 on 2026-03-07 06:07

from django.db import migrations


def _has_column(schema_editor, table_name, column_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            columns = connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return False
    return any(getattr(col, "name", None) == column_name for col in columns)


def check_and_rename_if_needed(apps, schema_editor):
    """
    This migration is a duplicate of 0012. Since 0012 already handled the rename,
    this migration should only run if is_featured still exists (which shouldn't happen).
    If is_trending already exists, do nothing.
    """
    has_is_featured = _has_column(schema_editor, "news_newsarticle", "is_featured")
    has_is_trending = _has_column(schema_editor, "news_newsarticle", "is_trending")

    # Only rename if is_featured exists and is_trending doesn't
    # (This shouldn't happen since 0012 already handled it, but just in case)
    if has_is_featured and not has_is_trending:
        schema_editor.execute(
            "ALTER TABLE news_newsarticle RENAME COLUMN is_featured TO is_trending"
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: rename is_trending back to is_featured if it exists
    """
    has_is_trending = _has_column(schema_editor, "news_newsarticle", "is_trending")
    has_is_featured = _has_column(schema_editor, "news_newsarticle", "is_featured")
    if has_is_trending and not has_is_featured:
        schema_editor.execute(
            "ALTER TABLE news_newsarticle RENAME COLUMN is_trending TO is_featured"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_is_featured_is_trending'),
    ]

    operations = [
        migrations.RunPython(check_and_rename_if_needed, reverse_migration),
    ]
