# Generated by Django 5.2.5 on 2026-03-07 06:48

from django.db import migrations, connection


def remove_epaper_edition_if_exists(apps, schema_editor):
    """
    Safely remove EpaperEdition model if it exists in the database.
    This handles cases where migration 0008 was already run.
    """
    with connection.cursor() as cursor:
        # Check if the table exists
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name='news_epaperedition'
        """)
        table_exists = cursor.fetchone() is not None
        
        if table_exists:
            # Delete the table
            cursor.execute("DROP TABLE IF EXISTS news_epaperedition")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: This is a no-op since we're removing a model.
    We cannot recreate the model without the epaper_upload_to function.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_is_featured_newsarticle_is_trending'),
    ]

    operations = [
        migrations.RunPython(remove_epaper_edition_if_exists, reverse_migration),
    ]
