# Generated by Django 5.2.5 on 2026-03-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_is_featured_newsarticle_is_trending_and_more'),
    ]

    operations = [
    ]
