# Generated by Django 5.2.5 on 2026-03-07 11:08

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_seed_gujarat_districts'),
    ]

    # Note: the `is_featured` → `is_trending` rename is already handled safely
    # in migrations 0012 and 0013 using custom SQL that tolerates missing
    # columns. To avoid errors on fresh databases where `is_featured` no longer
    # exists, this migration only (re)creates the EpaperEdition model.
    operations = [
        migrations.CreateModel(
            name='EpaperEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('pdf_file', models.FileField(help_text='Upload PDF file for the e-paper edition', upload_to=news.models.epaper_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-paper Edition',
                'verbose_name_plural': 'E-paper Editions',
                'ordering': ['-publication_date', '-created_at'],
                'indexes': [models.Index(fields=['publication_date'], name='news_epaper_publica_43b7f1_idx')],
            },
        ),
    ]
