# Generated by Django 5.2.5 on 2026-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_newsarticle_is_trending_reelcomment_reellike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
