# Generated by Django 5.2.5 on 2026-03-13 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_like_unique_like_per_user_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_editor_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_editor_pick', 'status', 'published_at'], name='news_newsar_is_edit_ad76b8_idx'),
        ),
    ]
