# Generated by Django 5.2.5 on 2026-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_add_is_editor_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelcontent',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['is_live', 'status', 'published_at'], name='news_videoc_is_live_27ea9a_idx'),
        ),
    ]
