# Generated by Django 5.2.5 on 2026-03-19 09:23

import news.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_remove_newsarticle_is_featured_poll_polloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.section_image_upload_to, validators=[utils.validators.validate_file_size, utils.validators.validate_image_size]),
        ),
    ]
