# Generated by Django 5.2.5 on 2026-04-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_remove_newsarticle_is_featured_section_image'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Some databases already removed this column in earlier manual/schema updates.
            # Keep migration idempotent to avoid ProgrammingError on missing column.
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "news_newsarticle" DROP COLUMN IF EXISTS "is_featured";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='newsarticle',
                    name='is_featured',
                ),
            ],
        ),
    ]
