# Generated by Django 5.2.5 on 2026-02-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('EDITOR', 'Editor'), ('REPORTER', 'Reporter'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
